services:

  collector:
    build:
      context: ./collector-api
    ports:
      - "3000:3000"
    env_file:
      - ./collector-api/.env

  normalizer:
    build:
      context: ./normalizer-api
    env_file:
      - ./normalizer-api/.env

  postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
      POSTGRES_DB: admetrics
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  mongodb:
    image: mongo:6
    ports:
      - "27017:27017"
    volumes:
      - mongodata:/data/db

volumes:
  pgdata:
  mongodata:
