services:

  ingestion:
    build:
      context: ./ingestion-api
    ports:
      - "3000:3000"
    env_file:
      - ./ingestion-api/.env

  normalizer:
    build:
      context: ./normalizer-worker
    env_file:
      - ./normalizer-worker/.env

  postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
      POSTGRES_DB: admetrics
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./normalizer-worker/init.sql:/docker-entrypoint-initdb.d/init.sql:ro

  mongodb:
    image: mongo:6
    ports:
      - "27017:27017"
    volumes:
      - mongodata:/data/db

volumes:
  pgdata:
  mongodata:
